Qovery/qovery-cli

api/account.go, api/api.go, api/application.go, api/branch.go, api/cloud.go, api/constants.go, api/project.go, api/repository.go, api/service.go, api/vars.go
- use http package constants http.MethodGet & http.MethodPost
- create constants.go with DefaultRootUrl value & header authorization constants
=> Use standard constants

cmd/upgrade.go
if /tmp is not on same fs os.rename will fail.
This fallback to a copy aside the original qovery cli, before overriding
it.
=> fix(upgrade): fallback to copy

cmd/upgrade.go, go.mod, go.sum
In order to self upgrade the binary, I've made this (not elegant) tricks
=> feat: adding upgrade in-place

cmd/init.go, util/templates.go
I also added support for putting .dockerignore in templates.
Why? We need to copy all files BESIDES node_modules in the gatsby template during the docker build, and there is no other way to exclude files than .dockerignore.
I'm pretty sure it will be also useful in other templates.
=> Init template flag

cmd/init.go, go.mod, io/git.go
Initialize new git repo after `qovery init -t`
=> add: init empty git repo in templates

cmd/admin_lock.go, cmd/admin_unlock.go, pkg/lock.go, pkg/version.go
Small PR to add two new admin commands to lock & unlock a cluster
=> feat: add admin cluster lock/unlock commands

cmd/admin.go, cmd/admin_lock.go, cmd/admin_locked_cluster.go, pkg/lock.go, pkg/version.go
Add reason when locking clusters.
**Do not merge for now as we need the API to be updated first**
=> feat: add reason to cluster locking

.gitignore, go.mod, go.sum, utils/context.go
https://github.com/Qovery/qovery-cli/security/dependabot/4
=> fix: upgrade jwt lib to fix security issue

cmd/admin_deploy_all.go, cmd/admin_deploy_failed_clusters.go, cmd/admin_update_all_kube.go, cmd/admin_vault_token.go, pkg/deploy.go
+ Also normalize command between separator with _ instead of -
=> Add admin endpoint to redeploy failed clusters

cmd/shell.go, pkg/version.go, utils/qovery.go
CL fixes `qovery shell <URL>` to work with console v3 new URLs.
=> fix: qovery shell <URL>

cmd/shell.go, pkg/version.go
- fix: shell new console URL
- chore: bump version
=> fix: shell new console url support

cmd/cronjob.go, cmd/cronjob_deploy.go, cmd/cronjob_update.go, cmd/lifecycle.go, cmd/lifecycle_update.go, pkg/version.go, utils/qovery.go
=> feat: add lifecycle and cronjob update commands

cmd/console.go, cmd/context.go, cmd/context_set.go, cmd/demo.go, cmd/env_import.go, cmd/log.go, cmd/port-forward.go, cmd/project_list.go, cmd/service_list.go, cmd/shell.go, cmd/status.go, pkg/version.go, utils/context.go, utils/posthog.go, utils/printer.go, utils/qovery.go
To improve the DevEx of the CLI - we automatically ask for the Qovery context if it's not set.
-> We also auto-set the context if it's obvious to guess the org, project, env, service.
=> Auto ask for qovery context if needed

cmd/cluster_install.go, cmd/demo.go, cmd/demo_destroy.go, cmd/demo_up.go, cmd/root.go, pkg/version.go, utils/context.go, utils/posthog.go
Hi, I improved the `qovery demo up` and `qovery demo destroy` commands to make them compliant with the other commands. Plus, I improved the Posthog analytics part.
=> Improve demo up|destroy commands

pkg/auth_service.go, utils/auth.go, utils/context.go
- Refacto to simplify the logic
- Use expiration from api response instead of hardcoded value
=> Fix refresh token logic

pkg/admin_cluster_services.go
+ For listing we should cluster list instead of cluster deploy
=> feat: propagate dry run up to api call

utils/context.go
To be able to use an JWT admin in the CI
=> chore: detect if the token is JWT or Token type

cmd/environment_stage_list.go, utils/qovery.go
- fixed display of helm name by adding the required method
- added stage id in `environment stage list` command
=> chore: fix helm name display and add stage id

pkg/shell.go
This PR adds:
- Properly handles user triggered exit in shell
- Triggers a reconnection if server connection is lost
Ticket: QOV-841
=> chore(QOV-841): prevent shell connection from closing

cmd/commands_list.go
=> feat(QOV-846): add a list-commands command

index.html
Enhanced robustness of this shell script in many areas
=> feat: add retry mechanism to CLI download

cmd/upgrade.go
The previous implementation of `qovery upgrade` attempted to delete the full temporary directory (`/tmp`) before extracting the new binary:
```go
if _, err := os.Stat(uncompressPath); !os.IsNotExist(err) {
err := os.RemoveAll(uncompressPath)
}
```
Since uncompressPath was set to os.TempDir() (usually /tmp), this would:
Attempt to remove sensitive system-managed files (e.g. /tmp/.X11-unix/X0)
Fail in environments like WSL2, macOS, or containers where /tmp is mounted as read-only
Cause upgrade crashes with errors like:
```
Error: error while removing uncompressed path: unlinkat //tmp/.X11-unix/X0: read-only file system
```
This PR improves the upgrade process by:
Replacing /tmp hardcoded paths with os.TempDir() and filepath.Join(...)
Only removing the specific files created during upgrade …
=> Fix qovery upgrade on WSL2/macOS by avoiding full /tmp deletion
