Qovery/qovery-cli

api/repository.go
This fixes the retrieval of environment variables during `qovery run` for the following case:
The local current repository URL (git remote origin) can be tweaked by the local CLI user.
For example, it can:
- contain an auth access token
- miss the trailing .git
ex: https://(optional-auth-token@)github.com/user/repo(.git)
We now attempt to remove these tweaks before comparing with URL candidates provided by the Qovery API.
=> Clean local repository URL in GetRepositoryByRemoteURL

cmd/root.go
An issue was reported indicating an invalid memory address or nil pointer
dereference according to the stacktrace:
```
qovery-cli/cmd.initSentry.func1(0xc00012edc0, 0xc0002ac240)
qovery-cli/qovery-cli/cmd/root.go:49 +0x2d
```
As the Stacktrace reference can technicaly be null (see `stacktrace.go`),
added some defensive checks on BeforeSend function
=> Fix potential invalid memory in ClientOptions.BeforeSend

cmd/root.go
Should not happen by design according to the client.go from sentry
dependency
But a panic runtime issue is still happening
=> Check that the BeforeSend event is not nil

.gitignore, default.nix, flake.lock, flake.nix, shell.nix
Hi Qovery :wave:,
I work at [Piana](https://github.com/getpiana) and we use [Nix](https://nixos.org/) to build our development environment. We also use your services for the deployment. We recently needed to use your CLI, so I integrated it inside our development environment. I decided to share the configuration so other Nix users could use it directly. Also, it could be nice to add the derivation to the [nixpkgs](https://github.com/NixOS/nixpkgs): this way your CLI could be accessible directly from their packages instead of building it. Let me know what you think about it.
=> Add Nix support

utils/qovery.go
By not handling the `RESTARTED` status, this will wait indefinitely for the target Environment to be ready when wanting to deploy a service / env
=> fix: Handle restarted status

cmd/application_update.go, cmd/container_update.go, cmd/lifecycle_update.go, utils/qovery.go
CLI service update didn't pass `AutoDeploy` param to qovery backend which fallbacks to `true` by default.
Ticket: ENG-1618
=> fix: pass autodeploy param to services update

cmd/database_deploy.go, utils/qovery.go
Add `--databases` option to `database deploy` so you can deploy a list of databases
Ticket: ENG-1617
=> feat: support deploying several db at once

utils/error.go, utils/qovery.go
Dedicated structure to return HTTP error messages. ATM only for DeployService method
=> chore: Improve HTTP error message response

cmd/admin_k9s.go, pkg/vault.go
=> chore: k9s to support GCP clusters

utils/qovery.go
Hi Team!
Ran into this bug this morning, it looks like the CronJob update logic had been updated last week && in that update, it runs a check for job.LifecycleJobResponse != nil, but then references the  job.LifecycleJobResponse in the "else" section. I *think* this is a typo & should be swapped to job.CronJobResponse. I've tested this locally & it has fixed the bug on my end.
The job.LifecycleJobResponse nil check: https://github.com/Qovery/qovery-cli/blob/main/utils/qovery.go#L2467
The current CLI output (the bug): 
```
qovery cronjob update --organization <org> --project <project> --environment <env> --tag <tag> -n <cronjobname> --image-name <image name>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x60 …
```
=> Bug Fix: Cannot Update Cronjobs/Consuming CronJobResponse when LifecycleJobResponse is nil

cmd/project.go, cmd/project_list.go
=> feat: add project list command

cmd/admin_cluster.go, cmd/admin_cluster_deploy.go, cmd/admin_cluster_list.go, pkg/admin_cluster_deploy_by_batch.go, pkg/admin_cluster_list.go, pkg/admin_cluster_services.go, pkg/delete_cluster.go, pkg/delete_orga.go, pkg/delete_project.go
The purpose of this PR is to introduce a new dedicated command to list / deploy & upgrade clusters.
`qovery admin cluster list --help`:
```
Flags:
-f, --filters stringToString   Value to filter the property selected (property-to-filter must be set as well) (default [])
-h, --help                     help for list
```
`qovery admin cluster deploy -help`:
```
Flags:
-y, --disable-dry-run          Disable dry run mode
-e, --execution-mode string    Batch execution mode - 'batch' will wait for the N deployments to be finished and ask validation to continue - 'on-the-fly' will deploy continuously as soon as a slot is available (default "batch")
-f, --filters stringToString   Value to filter the property selected (property-to-filter must be set as well) (default [])
-h, --help …
```
=> feat: Add cluster admin commands

cmd/application_env_update.go, cmd/container_env_update.go, cmd/cronjob_env_update.go, cmd/helm_env_update.go, cmd/lifecycle_env_update.go, utils/env_var.go
This PR adds support for updating Environment variables in lifecycle, application, container, helm and cronjob.
the commands will be as follows:
```
qovery lifecycle env update --organization test--project test --environment test --lifecycle test --key BRANCH_NAME --value test-pr
```
=>  feat: Add Update Environment Variable support

cmd/admin_cluster_deploy.go, pkg/version.go
To avoid mistakes, force the cluster statuses to be DEPLOYED if no status is used in the filters
=> fix: Use correct filter when forcing DEPLOYED clusters on deploy

cmd/root.go, utils/printer.go
It reports too many irrelevant issues (401, 404) and we dont look at it. To avoid maxing out our quota
=> Disable sentry

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/release_latest.yml, Dockerfile, cmd/environment_deploy.go, cmd/environment_statuses.go, go.mod
Adding `--skip-paused-services` flag to `environment deploy` command allowing to deploy all services from an environment but skip paused services.
Ticket: ENG-1708
=> feat: allow deploy env to skip stopped services

cmd/application.go, cmd/application_update.go
=> feat: allowing to set auto-deploy param on app update

cmd/demo.go, cmd/demo_scripts/create_qovery_demo.sh, cmd/demo_scripts/destroy_qovery_demo.sh, pkg/version.go
- Use powershell to automate setup on windows
- Use tmpdir to store files
- Mask error during destroy
=> Improve demo command

cmd/cluster_install.go, go.mod, go.sum
This PR includes two patches fixing the cluster install command:
1- Open API spec declaration was wrong, ContainerRegistryMirroringMode
should not be uppercase: fixed by bumping the Qovery SDK lib
2- Prompt was asking for a select for strorage class whereas it should
be a simple string
Ticket: COR-942
=> fix(COR-942): install cluster command

cmd/application_update.go, utils/qovery.go
I've posted a bug about this [on the forum](https://discuss.qovery.com/t/bug-errors-when-updating-an-application-with-the-cli/2785), so there are complete details there. The problem is that updating an application with the CLI doesn't work, at least in my situation, because it's not passing back the git token id that it got when querying the application data. The error it gets is:
```
{"type":"about:blank","title":"Bad Request","status":400,"detail":"You don't have any provider configured for GITHUB","instance":"/api/application/52d4d791-80ba-4d9d-8a6c-2dabe917b62d","message":"You don't have any provider configured for GITHUB"}
```
This changes it to pass the token id. I have confirmed that it works for updating my application.
=> fix: Update application update command to pass git token from the application

cmd/environment_cancel.go
=> fix(COR-842): allow to force cancel deployment

cmd/container_update.go, cmd/service_list.go, cmd/shell.go
Example:
```
qovery shell --organization <organization_name> --project <project_name> --environment <environment_name> --service <service_name>
qovery shell --organization <organization_name> --project <project_name> --environment <environment_name> --service <service_name> --pod <pod_name> --container <container_name> --command <command>
```
=> feat(shell): support context flags

.github/workflows/release.yml
remove useless lint on release action. Linting is already done on build
action.
=> ci: remove old lint on release action

cmd/admin.go, cmd/admin_cluster_deploy.go, pkg/admin_cluster_deploy_by_batch.go, pkg/admin_cluster_services.go
=> feat: Add no-confirm option to the cli

pkg/admin_cluster_services.go
* Remove hard limit of 100 for parallel runs
* Do not skip sleeping before checking cluster statuses on dry run update
=> chore: Improve admin cluster deploy command for CI use

cmd/root.go, utils/posthog.go, variable/notrack.go
add an env var to avoid sending command execution to our telemetry system (posthog)
=> feat: add QOVERY_TELEMETRY env var to avoid sending events to Qovery telemetry system

utils/context.go
This PR addresses [QOV-1127](https://qovery.atlassian.net/browse/QOV-1127) by adding calls to `os.Chmod` before each context file write.
The change is made at each write operation, and not only after file creation, in order to change the permissions of existing files created by previous versions.
[QOV-1127]: https://qovery.atlassian.net/browse/QOV-1127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix: set proper perms on context file at each create/update

Dockerfile
- Align with go.mod requirement (go 1.25.0)
- Fixes Docker build failure with v1.48.0
=> fix: update Dockerfile to use Go 1.25.1
